grpc:
  server:
    port: 9090

spring:
  application:
    name: gonlink
  data:
    mongodb:
      uri: mongodb+srv://sonnees:tCy7srcWvlHuxGnO@cluster0.m0vbmbu.mongodb.net/gonlink
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  jackson:
    time-zone: UTC
    time-zone-default: Asia/Ho_Chi_Minh

# global value
gonlink:
  public-method: online.gonlink.UrlShortener/generateShortCode, online.gonlink.UrlShortener/getOriginalUrl, online.gonlink.UrlShortener/getStringBase64Image, online.gonlink.UrlShortener/checkExistShortCode, online.gonlink.UrlShortener/checkNeedPasswordGetOriginalUrl
  allowed-characters: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  length-short-code: 6
  url-forbidden: rutlink.online, bom.to, bit.ly, bitly.com, ow.ly, shorturl.at, tinyurl.com, vnlink.top, Is.gd, rebrandly.com, tiny.cc, AdF.ly, MegaURL.in, Shrtfly.com, Shorte.st, Ouo.io, bit.do, s.pro.vn, short.com.vn, by.com.vn
  jwt:
    secret-key: 7b1f58b60b06295403c1887b7f258a955e2f594cec6c1fe12d80f6a247795fce
  qr:
    width: 200
    height: 200
    scalr:
      x: 25
      y: 25
      width: 50
      height: 50
  paging:
    page: 0
    size: 10
    sort-direction: ASC
  thread:
    fix-pool: 5

front-end:
  domain: http://localhost:5173/

