# docker-compose.yml
version: '3.8'

services:
  gonlink:  # Java service
    build:
      context: ./gonlink
      dockerfile: Dockerfile
    container_name: gonlink
    networks:
      - gonlink-network
    ports:
      - "9090:9090"

  grpc-gateway:  # Go service
    build:
      context: ./grpc-gateway
      dockerfile: Dockerfile
    container_name: grpc-gateway
    networks:
      - gonlink-network
    ports:
      - "8080:8080"
    environment:
      - GRPC_SERVER_ENDPOINT=gonlink:9090  # Cập nhật endpoint để trỏ đến service Java
      - GITHUB_CLIENT_ID=Ov23linxe63dBqWDk4fJ
      - GITHUB_CLIENT_SECRET=932406842c0a0f27e52990b3c5211a8854c3ef70
      - REDIRECT_URL=http://localhost:8080/auth/github/login/callback
      - GG_DOMAIN=http://localhost:8080
      - GG_CLIENT_ID=321176153256-m9eakfhp31ojm5e47c3v6r9hgkpnd4d2.apps.googleusercontent.com
      - GG_CLIENT_SECRET=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
      - GG_REDIRECT_URL=http://localhost:8080/auth/google/login/callback
      - JWT_SECRET=7b1f58b60b06295403c1887b7f258a955e2f594cec6c1fe12d80f6a247795fce
    depends_on:
      - gonlink

networks:
  gonlink-network:
    name: gonlink-network