package online.gonlink.exception.enumdef;

import io.grpc.Status;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ExceptionEnum {
    ACCOUNT_NOT_FOUND(Status.NOT_FOUND, "KHÔNG TÌM THẤY"),
    ACCOUNT_ME_SUCCESS(Status.OK, "THÀNH CÔNG"),
    ACCOUNT_REMOVE_URL_SUCCESS(Status.OK, "THÀNH CÔNG"),
    ACCOUNT_REMOVE_URL_FAIL(Status.CANCELLED, "THẤT BẠI"),
    ACCOUNT_APPEND_URL(Status.CANCELLED, "THẤT BẠI"),

    SHORTEN_GENERATE_SUCCESS(Status.OK, "THÀNH CÔNG"),
    SHORTEN_GENERATE_FAIL(Status.CANCELLED, "THẤT BẠI"),
    SHORTEN_GENERATE_ALREADY_EXISTS(Status.ALREADY_EXISTS, "SHORTEN_GENERATE_ALREADY_EXISTS"),
    DAY_TRAFFIC_INCREASE_FAIL(Status.CANCELLED, "DAY_TRAFFIC_INCREASE_FAIL"),
    MONTH_TRAFFIC_INCREASE_FAIL(Status.CANCELLED, "MONTH_TRAFFIC_INCREASE_FAIL"),
    GENERAL_TRAFFIC_INCREASE_FAIL(Status.CANCELLED, "GENERAL_TRAFFIC_INCREASE_FAIL"),

    QR_CODE_SUCCESS(Status.OK, "THÀNH CÔNG"),
    QR_CODE_FAIL(Status.CANCELLED, "THẤT BẠI"),

    SUCCESS(Status.OK, "THÀNH CÔNG"),
    UNAUTHENTICATED(Status.UNAUTHENTICATED, "KHÔNG ĐƯỢC PHÉP"),
    UNAUTHORIZED(Status.PERMISSION_DENIED, "KHÔNG CÓ QUYỀN"),
    FORBIDDEN_URL(Status.PERMISSION_DENIED, "FORBIDDEN_URL"),
    NOT_FOUND_URL(Status.NOT_FOUND, "NOT_FOUND_URL"),
    SHORT_CODE_NOT_FOUND(Status.NOT_FOUND, "NOT_FOUND"),
    NOT_FOUND_SHORT_CODE(Status.NOT_FOUND, "NOT_FOUND_SHORT_CODE"),
    EXIST_SHORT_CODE(Status.ALREADY_EXISTS, "EXIST_SHORT_CODE"),
    DATE_FORMAT(Status.FAILED_PRECONDITION, "DATE_FORMAT"),
    INTERNAL(Status.INTERNAL, "SERVER ĐANG GẶP LỖI"),

    /** RateLimitInterceptor */
    RLI_CREATE_BUCKET_FAIL(Status.INTERNAL, "RLI_CREATE_BUCKET_FAIL"),
    RLI_LIMIT_EXCEEDED(Status.RESOURCE_EXHAUSTED, "RLI_LIMIT_EXCEEDED"),

    /** HtmlSanitizerServiceImpl */
    HTML_SANITIZER(Status.CANCELLED, "Đã đạt giới hạn tạo bucket!"),
    PASSWORD_NOT_CORRECT(Status.PERMISSION_DENIED, "PASSWORD_NOT_CORRECT"),
    TIME_EXPIRED(Status.PERMISSION_DENIED, "TIME_EXPIRED"),
    MAX_ACCESS(Status.PERMISSION_DENIED, "MAX_ACCESS"),



    ;
    Status status;
    String message;
}
