spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb+srv://sonnees:8ymAG8ia1s88DwXO@cluster0.m0vbmbu.mongodb.net/AccountService
  jackson:
    time-zone: UTC
  kafka:
    bootstrap-servers: 9093
    consumer:
      group-id: account-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


# grpc
grpc:
  server:
    port: 9092

# global value


